# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BLKMoney' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for BLKMoney
pod 'MJExtension'
pod 'MJRefresh'
pod 'Masonry'
pod 'JKViewAnimation'
pod 'KMNavigationBarTransition'
end
